_: {
  base00 = "#2E3440"; # Nord0 - Polar Night (Darkest background)
  base01 = "#3B4252"; # Nord1 - Polar Night (Darker background/status bars)
  base02 = "#434C5E"; # Nord2 - Polar Night (Medium background/selection)
  base03 = "#4C566A"; # Nord3 - Polar Night (Lighter background/comments)
  base04 = "#D8DEE9"; # Nord4 - Snow Storm (Lighter foreground/subtle text)
  base05 = "#E5E9F0"; # Nord5 - Snow Storm (Default foreground/text)
  base06 = "#ECEFF4"; # Nord6 - Snow Storm (Lightest foreground/variables)
  base07 = "#ECEFF4"; # Often same as base06 or a pure white (using Nord6)
  base08 = "#BF616A"; # Nord11 - Aurora (Red/Errors)
  base09 = "#D08770"; # Nord12 - Aurora (Orange/Warnings)
  base0A = "#EBCB8B"; # Nord13 - Aurora (Yellow/Constants, Numbers)
  base0B = "#A3BE8C"; # Nord14 - Aurora (Green/Strings)
  base0C = "#8FBCBB"; # Nord7 - Frost (Aqua/Types)
  base0D = "#88C0D0"; # Nord8 - Frost (Light Blue/Functions, Identifiers)
  base0E = "#B48EAD"; # Nord15 - Aurora (Purple/Keywords)
  base0F = "#5E81AC"; # Nord10 - Frost (Indigo/Special use cases)
}
